### ISSUE TITLE
 LXHardwareSerial Serial2(2); //must be initialized before ESP32DMX

### ISSUE THREAD

**Issue by peteronksley** [claudeheintz/LXESP32DMX#4]
Hi Claude 

I hope you can help me, I have tried to use your RDMDeviceTest example on an esp32, but I am getting an error when I compile it, 
the error I am getting is

C:\Users\user\Documents\Arduino\libraries\LXESP32DMX-master\src\LXESP32DMX.cpp:23:25: error: conflicting declaration 'LXHardwareSerial Serial2'

 LXHardwareSerial Serial2(2); //must be initialized before ESP32DMX  

and also numerous Serial2 errors after this

I have changed the esp32-hal-uart.c file in the esp hardware folder as you instructed  but they was no difference in files so the error remained, 

I have reinstalled both esp32 and the LXESP32DMX.h library but still get the error, so I decided to try it on a different pc and still get the same error.

I am currently at a loss on how to correct it

yours

pete

**Comment by claudeheintz** [comment]
Hi,

The latest Espressif arduino-esp32 library defines Serial2 in HardwareSerial.h. &nbsp;So I have renamed Serial2 as LXSerial2 in the ESP32DMX library. &nbsp;I have not verified that the library works properly yet. &nbsp;However, the example file compiles correctly now.

-Claude Heintz
&nbsp;



On Fri, 31 Aug 2018 01:37:34 -0700, peteronksley  wrote:
&nbsp;
Hi Claude

I hope you can help me, I have tried to use your RDMDeviceTest example on an esp32, but I am getting an error when I compile it,
the error I am getting is

C:\Users\user\Documents\Arduino\libraries\LXESP32DMX-master\src\LXESP32DMX.cpp:23:25: error: conflicting declaration 'LXHardwareSerial Serial2'

LXHardwareSerial Serial2(2); //must be initialized before ESP32DMX

and also numerous Serial2 errors after this

I have changed the esp32-hal-uart.c file in the esp hardware folder as you instructed but they was no difference in files so the error remained,

I have reinstalled both esp32 and the LXESP32DMX.h library but still get the error, so I decided to try it on a different pc and still get the same error.

I am currently at a loss on how to correct it

yours

pete

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/claudeheintz/LXESP32DMX/issues/4",
"url": "https://github.com/claudeheintz/LXESP32DMX/issues/4",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": " LXHardwareSerial Serial2(2); //must be initialized before ESP32DMX (#4)",
"sections": [
{
"text": "",
"activityTitle": "**peteronksley**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@peteronksley",
"facts": [
{
"name": "Repository: ",
"value": "claudeheintz/LXESP32DMX"
},
{
"name": "Issue #: ",
"value": 4
}
]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"claudeheintz/LXESP32DMX\",\n\"issueId\": 4,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"claudeheintz/LXESP32DMX\",\n\"issueId\": 4\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/claudeheintz/LXESP32DMX/issues/4"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 374556788\n}"
}
],
"themeColor": "26292E"
}
]
